import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from '../components/providers';
import '../styles/global.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Nigol',
  description: 'Generated by Irachus'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      {/* <body className={`${inter.className} dark:bg-slate-800 bg-slate-50 fg  dark:text-white  text-black`}> */}
      <body className={inter.className}>
      <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
