import type { Metadata } from 'next';
import { Providers } from '../components/providers';
import '../styles/global.css';
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export const metadata: Metadata = {
  title: 'Nigol',
  description: 'Generated by Irachus'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body >
        <Providers>
          <main className='max-w-screen-xl '>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
